FROM alpine:3.17

LABEL author="Yongjie Zhuang"
LABEL descrption="Gatekeeper - Simple gateway written in Go"

RUN apk --no-cache add tzdata

WORKDIR /usr/src/

# binary is pre-compiled
COPY gatekeeper_build ./app_gatekeeper

ENV TZ=Asia/Shanghai

CMD ["./app_gatekeeper", "configFile=/usr/src/config/conf.yml"]

