FROM alpine:3.17

LABEL author="Yongjie Zhuang"
LABEL descrption="Mini file store"

RUN apk --no-cache add tzdata ffmpeg

WORKDIR /usr/src/

# binary is pre-compiled
COPY mini-fstore_build ./app_fstore

ENV TZ=Asia/Shanghai

CMD ["./app_fstore", "configFile=/usr/src/config/conf.yml"]
