mode.production: true

app.name: "fstore"

mysql:
  enabled: true
  user: "${MYSQL_USERNAME}"
  password: "${MYSQL_PASSWORD}"
  database: "mini_fstore"
  host: "${MYSQL_HOST}"
  port: 3306

redis:
  enabled: true
  address: "redis"
  port: 6379
  username:
  password:
  database: 0

rabbitmq:
  enabled: true
  host: "${RABBITMQ_ADDR}"
  port: 5672
  username: "${RABBITMQ_USERNAME}"
  password: "${RABBITMQ_PASSWORD}"
  vhost: "/"

server:
  host: "0.0.0.0"
  port: 8084
  gracefulShutdownTimeSec: 5
  perf.enabled: false

consul:
  enabled: true
  consulAddress: "${CONSUL_HOST}:8500"
  healthCheckUrl: /health
  healthCheckInterval: 120s
  healthCheckTimeout: 120s
  healthCheckFailedDeregisterAfter: 5s

logging.rolling.file: "/usr/src/logs/mini-fstore.log"

fstore:
  storage.dir: ${FSTORE_STORAGE}
  trash.dir: "${FSTORE_TRASH}"
  tmp.dir: "${FSTORE_TEMP}"
  backup:
    enabled: true
    secret: "${MINI_FSTORE_BACKUP_SECRET}"
