// auto generated by misoapi v0.1.6-beta.1 at 2024/09/10 21:16:37, please do not modify
package pump

import (
	"github.com/curtisnewbie/miso/miso"
)

func init() {
	miso.IPost("/api/v1/create-pipeline",
		func(inb *miso.Inbound, req ApiPipeline) (any, error) {
			return nil, ApiCreatePipeline(inb.Rail(), req)
		}).
		Desc("Create new pipeline. Duplicate pipeline is ignored, HA is not supported.")

	miso.IPost("/api/v1/remove-pipeline",
		func(inb *miso.Inbound, req ApiPipeline) (any, error) {
			return nil, ApiRemovePipeline(inb.Rail(), req)
		}).
		Desc("Remove existing pipeline. HA is not supported.")

	miso.Get("/api/v1/list-pipeline",
		func(inb *miso.Inbound) ([]Pipeline, error) {
			return ApiListPipelines(inb.Rail())
		}).
		Desc("List existing pipeline. HA is not supported.")

}
