CREATE DATABASE IF NOT EXISTS mini_fstore;

CREATE TABLE IF NOT EXISTS mini_fstore.file (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "primary key",
  file_id VARCHAR(32) NOT NULL COMMENT 'file id',
  name VARCHAR(255) NOT NULL COMMENT 'file name',
  status VARCHAR(10) NOT NULL COMMENT 'status',
  size BIGINT NOT NULL COMMENT 'size in bytes',
  md5 VARCHAR(32) NOT NULL COMMENT 'md5',
  upl_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'upload time',
  log_del_time TIMESTAMP NULL DEFAULT NULL COMMENT 'logic delete time',
  phy_del_time TIMESTAMP NULL DEFAULT NULL COMMENT 'physic delete time',
  UNIQUE KEY (file_id),
  KEY (md5)
) ENGINE=INNODB COMMENT 'File';
