// auto generated by misoapi v0.4.15-beta.2 at 2026/06/28 18:35:13 (CST), please do not modify
package web

import (
	"github.com/curtisnewbie/acct/internal/mflow"
	"github.com/curtisnewbie/miso/middleware/dbquery"
	"github.com/curtisnewbie/miso/miso"
)

func RegisterApi() {
	miso.HttpPost("/open/api/v1/cashflow/list", miso.AutoHandler(
		func(inb *miso.Inbound, req mflow.ListCashFlowReq) (miso.PageRes[mflow.ListCashFlowRes], error) {
			return ApiListCashFlows(inb.Rail(), dbquery.GetDB(), inb.Rail().User(), req)
		})).
		Extra(miso.ExtraName, "ApiListCashFlows").
		Resource(CodeManageCashflows)

	miso.HttpPost("/open/api/v1/cashflow/import/wechat", miso.ResHandler(
		func(inb *miso.Inbound) (any, error) {
			return nil, ApiImportWechatCashflows(inb, inb.Rail(), dbquery.GetDB(), inb.Rail().User())
		})).
		Extra(miso.ExtraName, "ApiImportWechatCashflows").
		Resource(CodeManageCashflows)

	miso.HttpGet("/open/api/v1/cashflow/list-currency", miso.ResHandler(
		func(inb *miso.Inbound) ([]string, error) {
			return ApiListCurrency(inb.Rail(), dbquery.GetDB(), inb.Rail().User())
		})).
		Extra(miso.ExtraName, "ApiListCurrency").
		Resource(CodeManageCashflows)

	miso.HttpPost("/open/api/v1/cashflow/list-statistics", miso.AutoHandler(
		func(inb *miso.Inbound, req mflow.ApiListStatisticsReq) (miso.PageRes[mflow.ApiListStatisticsRes], error) {
			return ApiListCashflowStatistics(inb.Rail(), dbquery.GetDB(), inb.Rail().User(), req)
		})).
		Extra(miso.ExtraName, "ApiListCashflowStatistics").
		Resource(CodeManageCashflows)

	miso.HttpPost("/open/api/v1/cashflow/plot-statistics", miso.AutoHandler(
		func(inb *miso.Inbound, req mflow.ApiPlotStatisticsReq) ([]mflow.ApiPlotStatisticsRes, error) {
			return ApiPlotCashflowStatistics(inb.Rail(), dbquery.GetDB(), inb.Rail().User(), req)
		})).
		Extra(miso.ExtraName, "ApiPlotCashflowStatistics").
		Resource(CodeManageCashflows)

}
