// auto generated by misoapi v0.2.0-beta.4 at 2025/07/07 22:46:07 (CST), please do not modify
package web

import (
	"github.com/curtisnewbie/mini-fstore/api"
	"github.com/curtisnewbie/mini-fstore/internal/fstore"
	"github.com/curtisnewbie/miso/miso"
)

func init() {
	miso.HttpGet("/file/stream", miso.RawHandler(ApiTempKeyStreamFile)).
		Extra(miso.ExtraName, "ApiTempKeyStreamFile").
		Desc(`Media streaming using temporary file key, the file_key's ttl is extended with each subsequent request. This endpoint is expected to be accessible publicly without authorization, since a temporary file_key is generated and used.`).
		Public().
		DocQueryParam("key", "temporary file key")

	miso.HttpGet("/file/raw", miso.RawHandler(ApiTempKeyDownloadFile)).
		Extra(miso.ExtraName, "ApiTempKeyDownloadFile").
		Desc(`Download file using temporary file key. This endpoint is expected to be accessible publicly without authorization, since a temporary file_key is generated and used.`).
		Public().
		DocQueryParam("key", "temporary file key")

	miso.HttpPut("/file", miso.ResHandler(
		func(inb *miso.Inbound) (string, error) {
			return ApiUploadFile(inb)
		})).
		Extra(miso.ExtraName, "ApiUploadFile").
		Desc(`Upload file. A temporary file_id is returned, which should be used to exchange the real file_id`).
		Resource(ResCodeFstoreUpload).
		DocHeader("filename", "name of the uploaded file")

	miso.HttpGet("/file/info", miso.AutoHandler(
		func(inb *miso.Inbound, req FileInfoReq) (api.FstoreFile, error) {
			return ApiGetFileInfo(inb, req)
		})).
		Extra(miso.ExtraName, "ApiGetFileInfo").
		Desc(`Fetch file info`)

	miso.HttpGet("/file/key", miso.AutoHandler(
		func(inb *miso.Inbound, req DownloadFileReq) (string, error) {
			return ApiGenFileKey(inb, req)
		})).
		Extra(miso.ExtraName, "ApiGenFileKey").
		Desc(`Generate temporary file key for downloading and streaming. This endpoint is expected to be called internally by another backend service that validates the ownership of the file properly.`)

	miso.HttpGet("/file/direct", miso.RawHandler(ApiDirectDownloadFile)).
		Extra(miso.ExtraName, "ApiDirectDownloadFile").
		Desc(`Download files directly using file_id. This endpoint is expected to be protected and only used internally by another backend service. Users can eaily steal others file_id and attempt to download the file, so it's better not be exposed to the end users.`).
		DocQueryParam("fileId", "actual file_id of the file record")

	miso.HttpDelete("/file", miso.AutoHandler(
		func(inb *miso.Inbound, req DeleteFileReq) (any, error) {
			return ApiDeleteFile(inb, req)
		})).
		Extra(miso.ExtraName, "ApiDeleteFile").
		Desc(`Mark file as deleted.`)

	miso.HttpPost("/file/unzip", miso.AutoHandler(
		func(inb *miso.Inbound, req api.UnzipFileReq) (any, error) {
			return ApiUnzipFile(inb, req)
		})).
		Extra(miso.ExtraName, "ApiUnzipFile").
		Desc(`Unzip archive, upload all the zip entries, and reply the final results back to the caller asynchronously`)

	miso.HttpPost("/backup/file/list", miso.AutoHandler(
		func(inb *miso.Inbound, req fstore.ListBackupFileReq) (fstore.ListBackupFileResp, error) {
			return ApiBackupListFiles(inb, req)
		})).
		Extra(miso.ExtraName, "ApiBackupListFiles").
		Desc(`Backup tool list files`).
		Public().
		DocHeader("Authorization", "Basic Authorization")

	miso.HttpGet("/backup/file/raw", miso.RawHandler(ApiBackupDownFile)).
		Extra(miso.ExtraName, "ApiBackupDownFile").
		Desc(`Backup tool download file`).
		Public().
		DocHeader("Authorization", "Basic Authorization").
		DocQueryParam("fileId", "actual file_id of the file record")

	miso.HttpPost("/maintenance/remove-deleted", miso.ResHandler(
		func(inb *miso.Inbound) (any, error) {
			return ApiRemoveDeletedFiles(inb)
		})).
		Extra(miso.ExtraName, "ApiRemoveDeletedFiles").
		Desc(`Remove files that are logically deleted and not linked (symbolically)`).
		Resource(ResCodeFstoreMaintenance)

	miso.HttpPost("/maintenance/sanitize-storage", miso.ResHandler(
		func(inb *miso.Inbound) (any, error) {
			return ApiSanitizeStorage(inb)
		})).
		Extra(miso.ExtraName, "ApiSanitizeStorage").
		Desc(`Sanitize storage, remove files in storage directory that don't exist in database`).
		Resource(ResCodeFstoreMaintenance)

	miso.HttpPost("/maintenance/compute-checksum", miso.ResHandler(
		func(inb *miso.Inbound) (any, error) {
			return ApiComputeChecksum(inb)
		})).
		Extra(miso.ExtraName, "ApiComputeChecksum").
		Desc(`Compute files' checksum if absent`)

	miso.HttpGet("/storage/info", miso.ResHandler(
		func(inb *miso.Inbound) (fstore.StorageInfo, error) {
			return ApiFetchStorageInfo(inb)
		})).
		Extra(miso.ExtraName, "ApiFetchStorageInfo").
		Desc(`Fetch storage info`).
		Resource(ResCodeFstoreMaintenance)

	miso.HttpGet("/storage/usage-info", miso.ResHandler(
		func(inb *miso.Inbound) ([]fstore.StorageUsageInfo, error) {
			return ApiFetchStorageUsageInfo(inb)
		})).
		Extra(miso.ExtraName, "ApiFetchStorageUsageInfo").
		Desc(`Fetch storage usage info`).
		Resource(ResCodeFstoreMaintenance)

	miso.HttpGet("/maintenance/status", miso.ResHandler(
		func(inb *miso.Inbound) (fstore.MaintenanceStatus, error) {
			return ApiFetchMaintenanceStatus()
		})).
		Extra(miso.ExtraName, "ApiFetchMaintenanceStatus").
		Desc(`Check server maintenance status`).
		Resource(ResCodeFstoreMaintenance)

}
