export const enUSDict = {
  "zh-CN": "中文",
  "en-US": "Eng",
  "folder": {
    newFolder: "New Folder",
    folderName: "Folder Name",
    create: "Create",
    virtualFolderName: "Virtual Folder Name:",
    openFolder: "Open Folder",
    listGrantedAccess: "List Granted Access",
    deleteFolder: "Delete Folder",
    createFolder: "Create Folder",
    deleteVirtualFolder: "Delete Virtual Folder",
    sureToDelete: "You sure you want to delete",
    virtualFolderRemoved: "Virtual Folder Removed",
    pleaseEnterFolderName: "Please enter folder name",
  },
  "operate-history": {
    operateHistory: "Operate History",
    fetch: "Fetch",
    userId: "User ID",
    user: "User",
    name: "Name",
    description: "Description",
    time: "Time",
    parameters: "Parameters",
  },
  "mng-note": {
    manageNote: "Manage Note",
    newNote: "New Note",
    title: "Title",
    content: "Content",
    save: "Save",
    keywords: "Keywords:",
    addNote: "Add Note",
    recordId: "RecordId",
    createdAt: "CreatedAt",
    updatedAt: "UpdatedAt",
    requestFailedUnknownError: "Request failed, unknown error",
  },
  "manage-logs": {
    systemErrorLogs: "System Error Logs",
    app: "App",
    caller: "Caller",
    msg: "Msg",
    time: "Time",
  },
  "user-detail": {
    userDetails: "User Details",
    userNo: "User No",
    role: "Role",
    registrationDate: "Registration Date",
    changePassword: "Change Password",
  },
  "register": {
    register: "Register",
    username: "Username",
    password: "Password",
    submit: "Submit",
    goToLoginPage: "Go to login page",
    pleaseEnterUsernameAndPassword: "Please enter username and password",
    registeredWaitForApproval: "Registered, please wait for administrator's approval",
  },
  "login": {
    login: "Login",
    username: "Username",
    password: "Password",
    submit: "Submit",
    dontHaveAccountRegisterFirst: "Don't have an account? Register first!",
    pleaseEnterUsernameAndPassword: "Please enter username and password",
  },
  "manage-resources": {
    manageResources: "Manage Resources",
    resourceName: "Resource Name",
    resourceCode: "Resource Code",
    create: "Create",
    newResource: "New Resource",
    id: "ID",
    name: "Name",
    code: "Code",
    createBy: "Create By",
    createTime: "Create Time",
    updateBy: "Update By",
    updateTime: "Update Time",
    pleaseEnterNewResourceName: "Please enter new resource name",
    pleaseEnterNewResourceCode: "Please enter new resource code",
  },
  "manage-paths": {
    managePaths: "Manage Paths",
    method: "Method",
    pathPattern: "Path Pattern",
    group: "Group",
    type: "Type:",
    bindToResourceOptional: "Bind To Resource (optional)",
    description: "Description",
    create: "Create",
    pathUrl: "Path URL:",
    newPath: "New Path",
    id: "ID",
    url: "URL",
    public: "Public",
    protected: "Protected",
    createBy: "Create By",
    createTime: "Create Time",
    requestFailedUnknownError: "Request failed, unknown error",
  },
  "manage-role": {
    manageRoles: "Manage Roles",
    roleName: "Role Name",
    create: "Create",
    newRole: "New Role",
    role: "Role",
    roleNo: "Role No",
    createBy: "Create By",
    createTime: "Create Time",
    updateBy: "Update By",
    updateTime: "Update Time",
    pleaseEnterNewRoleName: "Please enter new role name",
  },
  "manager-user": {
    manageUser: "Manage User",
    addUser: "Add User",
    newUser: "New User",
    username: "Username",
    password: "Password",
    userRole: "User Role",
    add: "Add User",
    searchUsername: "Username:",
    role: "Role",
    status: "Status",
    userNo: "User No",
    name: "Name",
    reviewStatus: "Review Status",
    createBy: "Create By",
    createTime: "Create Time",
    updateBy: "Update By",
    updateTime: "Update Time",
    disabled: "disabled",
    normal: "normal",
    rejected: "rejected",
    approved: "approved",
    pending: "pending",
    deleteUser: "Delete User",
    sureToDeleteUser: "You sure you want to delete user",
    approveRegistration: "Approve Registration",
    rejectRegistration: "Reject Registration",
    resetLogin: "Reset Login",
    pleaseEnterUsernameAndPassword: "Please enter username and password",
    requestFailedUnknownError: "Request failed, unknown error",
  },
  "manage-keys": {
    manageKeys: "Manage Keys",
    generateKey: "Generate Key",
    generateNewUserKey: "Generate New User Key",
    keyName: "Key Name",
    confirmPassword: "Confirm Password",
    generate: "Generate",
    tokenName: "Token Name:",
    secretKey: "Secret Key",
    name: "Name",
    expirationTime: "Expiration Time",
    createTime: "Create Time",
    delete: "Delete",
    copyKey: "Copy Key",
    pleaseEnterPassword: "Please enter password",
    pleaseEnterKeyName: "Please enter key name",
  },
  "change-password": {
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    submit: "Submit",
    pleaseEnterPasswords: "Please enter passwords",
    confirmedPasswordNotMatched: "Confirmed password is not matched",
    newPasswordMustBeDifferent: "new password must be different",
    passwordChanged: "Password changed",
  },
  "bookmark-blacklist": {
    chromeBookmarkBlacklist: "Chrome Bookmark Blacklist",
    searchName: "Search Name",
    id: "ID",
    name: "Name",
    operation: "Operation",
    removeBookmarkBlacklist: "Remove Bookmark Blacklist",
    removingBookmarkBlacklist: "Removing Bookmark Blacklist",
  },
  "manage-bookmarks": {
    chromeBookmarks: "Chrome Bookmarks",
    uploadBookmarkFiles: "Upload Bookmark Files:",
    upload: "Upload",
    searchName: "Search Name",
    id: "ID",
    name: "Name",
    operation: "Operation",
    bookmarksUploaded: "Bookmarks uploaded",
    pleaseSelectFile: "Please select file",
    removeBookmark: "Remove Bookmark",
    removingBookmark: "Removing Bookmark",
  },
  "access-log": {
    loginHistory: "Login History",
    id: "Id",
    user: "User",
    accessTime: "Access time",
    success: "Success",
    ipAddress: "IP Address",
    userAgent: "User Agent",
    url: "URL",
    true: "True",
    false: "False",
  },
  "manage-files": {
    name: "Name",
    skipByName: "Skip Uploaded Files (By Name)",
    progress: "Progress: ",
    orderByName: "Order By Name",
    preview: "Preview",
    inDir: "In Directory",
    uploader: "Uploader",
    uploadTime: "Upload Time",
    dirName: "Directory Name",
    newDir: "New Directory",
    size: "Size",
    operation: "Operation",
    file: "File",
    all: "All",
    directory: "Directory",
    fileType: "File Type",
    upload: "Upload",
    cancel: "Cancel",
    submit: "Submit",
    virtualFolder: "Virtual Folder:",
    fileKey: "File Key",
    bookmarkFilesBatchOp: "Bookmark files to undertake batch operation",
    showDirTree: "Show directory tree",
    makeNewDir: "Make New Directory",
    nameOfDirBelongs: "Name of directory that each file belongs to",
    type: "Type",
    updateTime: "Update Time",
    goUpOneLevel: "Go up one level of the directory tree",
    bookmarkFileForBatchOp: "Bookmark file for batch operation. Click row with meta key for convenience.",
    truncateDir: "Truncate directory",
    shareByLink: "Share By Link",
    shareByQRCode: "Share By QRCode",
    unzipToDir: "Unzip To Directory",
  },
  "dir-tree-nav": {
    searchDirName: "Search Dir Name",
    defaultTitle: "Directory Tree Navigation",
  },
  "list-notification": {
    platformNotification: "Platform Notifications",
    unreadOnly: "Unread Only",
    markAllOpened: "Mark All Opened",
    notificationNo: "Notification No",
    title: "Title",
    brief: "Brief",
    status: "Status",
    createTime: "Create Time",
  },
  nav: {
    menu: "Menu",
    fileAndGallery: "File & Gallery",
    manageFiles: "Manage Files",
    galleries: "Galleries",
    virtualFolders: "Virtual Folders",
    versionedFiles: "Versioned Files",
    browseHistory: "Browse History",
    doc: "Documents",
    bookmarks: "Bookmarks",
    bookmarkBlacklist: "Bookmark Blacklists",
    logout: "Logout",
    admin: "Admin",
    user: "User",
    site: "Site",
    finance: "Finance",
    drone: "Drone",
    userDetails: "User Details",
    manageKeys: "Manage Keys",
    loginHistory: "Login History",
    notes: "Notes",
    websitePasswords: "Website Passwords",
    manageUsers: "Manage Users",
    manageRoles: "Manage Roles",
    managePaths: "Manage Paths",
    manageResources: "Manage Resources",
    systemErrLogs: "System Error Logs",
    systemStorage: "File Storage",
    eventPumpDashboard: "Event-Pump Dashboard",
    cashflows: "Cashflows",
    cashflowsStats: "Cashflows Statistics",
    droneTasks: "Drone Tasks",
  },
  "pdf-viewer": {
    noFileSelected: "No PDF selected. Consider picking one to read?",
    importCashflows: "Import ${importType} Cashflows:"
  },
  gallery: {
    createNew: "Create New Gallery",
    galleryName: "Gallery Name",
    create: "Create",
    createGallery: "Create Gallery",
    galleries: "Galleries",
    browse: "Browse",
    directory: "Directory",
    share: "Share",
    delete: "Delete",
    update: "Update",
  },
  "gallery-access": {
    grantAccess: "Grant Access",
    grantingAccessTo: "Granting access to '${name}'",
    username: "Username",
    submit: "Submit",
    noAccessGrantedYet: "You haven't granted access to any one yet",
    usersGrantedAccess: "Users Granted Access To This Gallery:",
    dateGranted: "Date Granted",
    removeAccess: "Remove Access",
    remove: "Remove",
    close: "Close",
    enterUsernameFirst: "Enter username first",
    accessGranted: "Access granted",
  },
};

export const zhCNDict = {
  "zh-CN": "中文",
  "en-US": "Eng",
  "folder": {
    newFolder: "新文件夹",
    folderName: "文件夹名称",
    create: "创建",
    virtualFolderName: "虚拟文件夹名称:",
    openFolder: "打开文件夹",
    listGrantedAccess: "查看授权访问",
    deleteFolder: "删除文件夹",
    createFolder: "创建文件夹",
    deleteVirtualFolder: "删除虚拟文件夹",
    sureToDelete: "您确定要删除",
    virtualFolderRemoved: "虚拟文件夹已删除",
    pleaseEnterFolderName: "请输入文件夹名称",
  },
  "operate-history": {
    operateHistory: "操作历史",
    fetch: "获取",
    userId: "用户ID",
    user: "用户",
    name: "名称",
    description: "描述",
    time: "时间",
    parameters: "参数",
  },
  "mng-note": {
    manageNote: "笔记管理",
    newNote: "新笔记",
    title: "标题",
    content: "内容",
    save: "保存",
    keywords: "关键词:",
    addNote: "添加笔记",
    recordId: "记录ID",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    requestFailedUnknownError: "请求失败,未知错误",
  },
  "manage-logs": {
    systemErrorLogs: "系统错误日志",
    app: "应用",
    caller: "调用者",
    msg: "消息",
    time: "时间",
  },
  "user-detail": {
    userDetails: "用户详情",
    userNo: "用户编号",
    role: "角色",
    registrationDate: "注册日期",
    changePassword: "修改密码",
  },
  "register": {
    register: "注册",
    username: "用户名",
    password: "密码",
    submit: "提交",
    goToLoginPage: "前往登录页面",
    pleaseEnterUsernameAndPassword: "请输入用户名和密码",
    registeredWaitForApproval: "注册成功,请等待管理员批准",
  },
  "login": {
    login: "登录",
    username: "用户名",
    password: "密码",
    submit: "提交",
    dontHaveAccountRegisterFirst: "还没有账号?先注册!",
    pleaseEnterUsernameAndPassword: "请输入用户名和密码",
  },
  "manage-resources": {
    manageResources: "资源管理",
    resourceName: "资源名称",
    resourceCode: "资源代码",
    create: "创建",
    newResource: "新资源",
    id: "ID",
    name: "名称",
    code: "代码",
    createBy: "创建者",
    createTime: "创建时间",
    updateBy: "更新者",
    updateTime: "更新时间",
    pleaseEnterNewResourceName: "请输入新资源名称",
    pleaseEnterNewResourceCode: "请输入新资源代码",
  },
  "manage-paths": {
    managePaths: "路径管理",
    method: "方法",
    pathPattern: "路径模式",
    group: "分组",
    type: "类型:",
    bindToResourceOptional: "绑定到资源(可选)",
    description: "描述",
    create: "创建",
    pathUrl: "路径URL:",
    newPath: "新路径",
    id: "ID",
    url: "URL",
    public: "公开",
    protected: "受保护",
    createBy: "创建者",
    createTime: "创建时间",
    requestFailedUnknownError: "请求失败,未知错误",
  },
  "manage-role": {
    manageRoles: "角色管理",
    roleName: "角色名称",
    create: "创建",
    newRole: "新角色",
    role: "角色",
    roleNo: "角色编号",
    createBy: "创建者",
    createTime: "创建时间",
    updateBy: "更新者",
    updateTime: "更新时间",
    pleaseEnterNewRoleName: "请输入新角色名称",
  },
  "manager-user": {
    manageUser: "用户管理",
    addUser: "添加用户",
    newUser: "新用户",
    username: "用户名",
    password: "密码",
    userRole: "用户角色",
    add: "添加用户",
    searchUsername: "用户名:",
    role: "角色",
    status: "状态",
    userNo: "用户编号",
    name: "名称",
    reviewStatus: "审核状态",
    createBy: "创建者",
    createTime: "创建时间",
    updateBy: "更新者",
    updateTime: "更新时间",
    disabled: "已禁用",
    normal: "正常",
    rejected: "已拒绝",
    approved: "已批准",
    pending: "待审核",
    deleteUser: "删除用户",
    sureToDeleteUser: "您确定要删除用户",
    approveRegistration: "批准注册",
    rejectRegistration: "拒绝注册",
    resetLogin: "重置登录",
    pleaseEnterUsernameAndPassword: "请输入用户名和密码",
    requestFailedUnknownError: "请求失败,未知错误",
  },
  "manage-keys": {
    manageKeys: "密钥管理",
    generateKey: "生成密钥",
    generateNewUserKey: "生成新用户密钥",
    keyName: "密钥名称",
    confirmPassword: "确认密码",
    generate: "生成",
    tokenName: "令牌名称:",
    secretKey: "密钥",
    name: "名称",
    expirationTime: "过期时间",
    createTime: "创建时间",
    delete: "删除",
    copyKey: "复制密钥",
    pleaseEnterPassword: "请输入密码",
    pleaseEnterKeyName: "请输入密钥名称",
  },
  "change-password": {
    changePassword: "修改密码",
    currentPassword: "当前密码",
    newPassword: "新密码",
    confirmNewPassword: "确认新密码",
    submit: "提交",
    pleaseEnterPasswords: "请输入密码",
    confirmedPasswordNotMatched: "确认密码不匹配",
    newPasswordMustBeDifferent: "新密码必须与当前密码不同",
    passwordChanged: "密码已修改",
  },
  "bookmark-blacklist": {
    chromeBookmarkBlacklist: "Chrome 书签黑名单",
    searchName: "搜索名称",
    id: "ID",
    name: "名称",
    operation: "操作",
    removeBookmarkBlacklist: "删除书签黑名单",
    removingBookmarkBlacklist: "正在删除书签黑名单",
  },
  "manage-bookmarks": {
    chromeBookmarks: "Chrome 书签",
    uploadBookmarkFiles: "上传书签文件:",
    upload: "上传",
    searchName: "搜索名称",
    id: "ID",
    name: "名称",
    operation: "操作",
    bookmarksUploaded: "书签已上传",
    pleaseSelectFile: "请选择文件",
    removeBookmark: "删除书签",
    removingBookmark: "正在删除书签",
  },
  "access-log": {
    loginHistory: "登陆历史",
    id: "ID",
    user: "用户",
    accessTime: "访问时间",
    success: "成功",
    ipAddress: "IP 地址",
    userAgent: "用户代理",
    url: "URL",
    true: "是",
    false: "否",
  },
  "manage-files": {
    name: "文件名",
    skipByName: "忽略名称重复文件",
    progress: "上传进度: ",
    orderByName: "根据名称排序",
    preview: "预览",
    inDir: "归属文件夹",
    uploader: "上传者",
    uploadTime: "上传时间",
    dirName: "文件夹名称",
    newDir: "新文件夹",
    size: "大小",
    operation: "操作",
    all: "全部",
    file: "文件",
    directory: "文件夹",
    fileType: "文件类型",
    upload: "上传",
    cancel: "取消",
    submit: "提交",
    virtualFolder: "虚拟文件夹:",
    fileKey: "文件键",
    bookmarkFilesBatchOp: "收藏文件以进行批量操作",
    showDirTree: "显示文件夹树",
    makeNewDir: "新建文件夹",
    nameOfDirBelongs: "每个文件所属的文件夹名称",
    type: "类型",
    updateTime: "更新时间",
    goUpOneLevel: "返回上一级目录",
    bookmarkFileForBatchOp: "收藏文件以便批量操作。按住元键点击行更便捷。",
    truncateDir: "清空文件夹",
    shareByLink: "通过链接分享",
    shareByQRCode: "通过二维码分享",
    unzipToDir: "解压到文件夹",
  },
  "dir-tree-nav": {
    searchDirName: "搜索文件夹名称",
    defaultTitle: "文件夹快速跳转",
  },
  "list-notification": {
    platformNotification: "站内通知",
    unreadOnly: "未读通知",
    markAllOpened: "全部已读",
    notificationNo: "通知标题",
    title: "标题",
    brief: "内容",
    status: "状态",
    createTime: "创建时间",
  },
  nav: {
    menu: "菜单",
    fileAndGallery: "文件 & 画廊",
    manageFiles: "文件管理",
    galleries: "画廊",
    virtualFolders: "虚拟文件夹",
    versionedFiles: "版本文件",
    browseHistory: "浏览历史",
    doc: "文档管理",
    bookmarks: "书签",
    bookmarkBlacklist: "书签黑名单",
    logout: "退出登陆",
    admin: "管理",
    user: "用户",
    site: "站点",
    finance: "财务",
    drone: "Drone",
    userDetails: "用户详情",
    manageKeys: "密钥管理",
    loginHistory: "登陆历史",
    notes: "笔记",
    websitePasswords: "网站密码",
    manageUsers: "用户管理",
    manageRoles: "角色管理",
    managePaths: "路径管理",
    manageResources: "资源管理",
    systemErrLogs: "系统异常日志",
    systemStorage: "文件存储",
    eventPumpDashboard: "Event-Pump 面板",
    cashflows: "流水记录",
    cashflowsStats: "流水统计",
    droneTasks: "Drone 任务",
  },
  "pdf-viewer": {
    noFileSelected: "请先选择 PDF 文件",
  },
  gallery: {
    createNew: "创建画廊",
    galleryName: "画廊名称",
    create: "创建",
    createGallery: "创建画廊",
    galleries: "画廊",
    browse: "浏览",
    directory: "跳转文件夹",
    share: "分享",
    delete: "删除",
    update: "更新",
  },
  "gallery-access": {
    grantAccess: "授权访问",
    grantingAccessTo: "正在授权访问 '${name}'",
    username: "用户名",
    submit: "提交",
    noAccessGrantedYet: "您尚未向任何人授予访问权限",
    usersGrantedAccess: "已授予此画廊访问权限的用户:",
    dateGranted: "授权日期",
    removeAccess: "移除访问权限",
    remove: "移除",
    close: "关闭",
    enterUsernameFirst: "请先输入用户名",
    accessGranted: "访问权限已授予",
  },
};
