export const enUSDict = {
  "zh-CN": "Chinese",
  "en-US": "English",
  "manage-files": {
    name: "Name",
    skipByName: "Skip Uploaded Files (By Name)",
    progress: "Progress: ",
    orderByName: "Order By Name",
    preview: "Preview",
    inDir: "In Directory",
    uploader: "Uploader",
    uploadTime: "Upload Time",
    dirName: "Directory Name",
    newDir: "New Directory",
    size: "Size",
    operation: "Operation",
    file: "File",
    all: "All",
    directory: "Directory",
    fileType: "File Type",
    upload: "Upload",
  },
  "dir-tree-nav": {
    searchDirName: "Search Dir Name",
    defaultTitle: "Directory Tree Navigation",
  },
  nav: {
    fileAndGallery: "File & Gallery",
    manageFiles: "Manage Files",
    galleries: "Galleries",
    virtualFolders: "Virtual Folders",
    versionedFiles: "Versioned Files",
    browseHistory: "Browse History",
    doc: "Documents",
    bookmarks: "Bookmarks",
    bookmarkBlacklist: "Bookmark Blacklists",
    logout: "Logout",
  },
  "pdf-viewer": {
    noFileSelected: "No PDF selected. Consider picking one to read?",
  },
  gallery: {
    createNew: "Create New Gallery",
    galleryName: "Gallery Name",
    create: "Create",
    createGallery: "Create Gallery",
    galleries: "Galleries",
    browse: "Browse",
    directory: "Directory",
    share: "Share",
    delete: "Delete",
    update: "Update",
  },
};

export const zhCNDict = {
  "zh-CN": "中文",
  "en-US": "英文",
  "manage-files": {
    name: "文件名",
    skipByName: "忽略名称重复文件",
    progress: "上传进度: ",
    orderByName: "根据名称排序",
    preview: "预览",
    inDir: "归属文件夹",
    uploader: "上传者",
    uploadTime: "上传时间",
    dirName: "文件夹名称",
    newDir: "新文件夹",
    size: "大小",
    operation: "操作",
    all: "全部",
    file: "文件",
    directory: "文件夹",
    fileType: "文件类型",
    upload: "上传",
  },
  "dir-tree-nav": {
    searchDirName: "搜索文件夹名称",
    defaultTitle: "文件夹快速跳转",
  },
  nav: {
    fileAndGallery: "文件 & 画廊",
    manageFiles: "文件管理",
    galleries: "画廊",
    virtualFolders: "虚拟文件夹",
    versionedFiles: "版本文件",
    browseHistory: "浏览历史",
    doc: "文档管理",
    bookmarks: "书签",
    bookmarkBlacklist: "书签黑名单",
    logout: "退出登陆",
  },
  "pdf-viewer": {
    noFileSelected: "请先选择 PDF 文件",
  },
  gallery: {
    createNew: "创建画廊",
    galleryName: "画廊名称",
    create: "创建",
    createGallery: "创建画廊",
    galleries: "画廊",
    browse: "浏览",
    directory: "跳转文件夹",
    share: "分享",
    delete: "删除",
    update: "更新",
  },
};
